### ISSUE TITLE
Unexpected end of input.

### ISSUE THREAD

**Issue by FieldMarshallVague** [Fyrd/caniuse#2038]
Hi,

I'm getting this error when running a gulp build:

```
PS C:\myproj> gulp
module.js:453
    throw err;
    ^

SyntaxError: C:\myproj\node_modules\gulp-autoprefixer\node_modules
\autoprefixer-core\node_modules\caniuse-db\data.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:450:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\myproj\node_modules\gulp-autoprefixe
r\node_modules\autoprefixer-core\node_modules\browserslist\index.js:1:77)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
PS C:\myproj>
```

I'm using Node 4.2.1 and NPM 3.3.9.  According to the package.json, CanIUse is v. 1.0.30000344.  The problem seems to be the caniuse data.json file, but I can't see anyone else with this problem.  Is this a missing ';' from the source?  Or something wrong with my setup?

Any help appreciated, cheers.

**Comment by Fyrd** [comment]
I really have no idea what could have caused this. Maybe try deleting caniuse-db and running npm install again? AFAICT there's currently no problem with the data.

**Comment by FieldMarshallVague** [comment]
OK, thanks for looking.  I tried that and it was enough to get me a different error (in another module).
