### ISSUE TITLE
Cannot read property 'stats' of undefined

### ISSUE THREAD

**Issue by pixelass** [Fyrd/caniuse#3441]
Getting this error from a package that uses this library (postcss-cssnext)

```shell
$ NODE_ENV=production node ./scripts/build 
<PROJECT_FOLDER>/node_modules/caniuse-api/dist/index.js:68
    return data.stats[browser[0]] && data.stats[browser[0]][browser[1]] === "y";
               ^

TypeError: Cannot read property 'stats' of undefined
    at<PROJECT_FOLDER>/node_modules/caniuse-api/dist/index.js:68:16
    at Array.every (native)
    at isSupported (<PROJECT_FOLDER>/node_modules/caniuse-api/dist/index.js:67:6)
    at <PROJECT_FOLDER>/node_modules/postcss-cssnext/lib/index.js:69:117
    at Array.forEach (native)
    at <PROJECT_FOLDER>node_modules/postcss-cssnext/lib/index.js:56:35
    at creator (/Users/pixelass/Workspace/private/npm-boilerplate/node_modules/postcss/lib/postcss.js:150:35)
    at inputFiles.forEach.file <PROJECT_FOLDER>/scripts/run-build.js:107:17)
    at Array.forEach (native)
    at err (<PROJECT_FOLDER>/scripts/run-build.js:71:16)
error Command failed with exit code 1.

```

**Comment by Vinnl** [comment]
As described in https://github.com/MoOx/postcss-cssnext/issues/381, this isn't an issue with caniuse, but with postcss-cssnext depending on a version of caniuse-db that is too old.

**Comment by pixelass** [comment]
thx for the link
