### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'ie' in undefined:  Getting Error validate-jsons.js

### ISSUE THREAD

**Issue by qadeerqureshi** [Fyrd/caniuse#3578]
I executed validate-jsons.js on data.json and its throwing error.

`TypeError: Cannot use 'in' operator to search for 'ie' in undefined
    at Validator.validateKeys (C:\Users\Qadeer.a\Documents\caniuse-master\validator\validate-jsons.js:186:30)
    at Validator.validateSupportData (C:\Users\Qadeer.a\Documents\caniuse-master\validator\validate-jsons.js:216:18)
    at Validator.validateFeature (C:\Users\Qadeer.a\Documents\caniuse-master\validator\validate-jsons.js:250:18)
    at new Validator (C:\Users\Qadeer.a\Documents\caniuse-master\validator\validate-jsons.js:284:22)
    at processFile (C:\Users\Qadeer.a\Documents\caniuse-master\validator\validate-jsons.js:309:13)
    at C:\Users\Qadeer.a\Documents\caniuse-master\validator\validate-jsons.js:319:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
`

**Comment by Fyrd** [comment]
Not seeing any issues according to Travis CI at https://travis-ci.org/Fyrd/caniuse/ . Perhaps fetch the latest data and try again?

**Comment by qadeerqureshi** [comment]
At this line 323, i changed from sample-data.json to data.json. In response i get this error. 

https://github.com/Fyrd/caniuse/blob/master/validator/validate-jsons.js#L323

**Comment by harunoz** [comment]
I encountered the same issue.
