### ISSUE TITLE
The note about Safari's partial support does not appear on the WebCodec page

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6984]
<img width="833" alt="Screenshot 2024-02-27 at 12 08 52 PM" src="https://github.com/Fyrd/caniuse/assets/108474/09e0de97-68f6-4d41-bfc5-3812e60815a5">

There's no note for why Can I Use considers Safari to only have partial support for WebCodecs API.

Why?

**Comment by jensimmons** [comment]
In the code for the JSON file I see
```
 "notes_by_num":{
    "1":"Video-only support"
  },
```

Weird that the note does not appear on the page.

**Comment by Schweinepriester** [comment]
Can reproduce, seems like a bug!

There's an error in the console as well:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'split')
    at CiuFeatureTabs.renderBaselineNote (ciu-feature-tabs.ts:157:26)
    at CiuFeatureTabs.renderNotes (ciu-feature-tabs.ts:188:12)
    at CiuFeatureTabs.renderTabContent (ciu-feature-tabs.ts:477:17)
    at CiuFeatureTabs.render (ciu-feature-tabs.ts:508:13)
    at CiuFeatureTabs.update (lit-element.ts:293:33)
    at CiuFeatureTabs.performUpdate (updating-element.ts:774:14)
    at CiuFeatureTabs._enqueueUpdate (updating-element.ts:724:25)
```

**Comment by Fyrd** [comment]
Yup, it wasn't showing up because of that bug. Has now been fixed, thanks for reporting!
